// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://azfnawxnearrtltvzrxv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF6Zm5hd3huZWFycnRsdHZ6cnh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4NDQ3MDUsImV4cCI6MjA2MzQyMDcwNX0.Nbt_qoW8_6xroiGPRQAwjeEVz8hSZk32HuT2mMwRmiY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);